#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  is_prime.py
#  
#  Copyright 2016 keshanna <keshanna@VATAPI>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
#  
#ver1
import math


prime = input("Enter the number to check:")
max = int(math.sqrt(float(prime)))

print "Will check until",max,"+1"
#Just take the next no. to max
nmax = max + 1
i = 0
if (prime % 2 == 0):
	print prime,"is an even number, So, it is not prime"
else:
	print prime," is not even number, Starting to check for prime no...\
begins"
	for i in range(3,nmax,1):
		print "Checking with ", i
		if ((prime % i) == 0):
			print i,"divides",prime
			break
			#exit # This does not exit the for loop, Loop continues
		else:
			print i,"does not divides", prime
	#else:

		print "i is now",i	
if (i>= max):
	print i,"is >=",max, "So, ",prime, " is a prime number"
else:
	print i," < ", max, "So, ",prime, " is not prime no....."
