#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
##Problem 30
##==========


   ##Surprisingly there are only three numbers that can be written as the sum
   ##of fourth powers of their digits:

     ##1634 = 1^4 + 6^4 + 3^4 + 4^4
     ##8208 = 8^4 + 2^4 + 0^4 + 8^4
     ##9474 = 9^4 + 4^4 + 7^4 + 4^4

   ##As 1 = 1^4 is not a sum it is not included.

   ##The sum of these numbers is 1634 + 8208 + 9474 = 19316.

   ##Find the sum of all the numbers that can be written as the sum of fifth
   ##powers of their digits.

   
   ##Answer: 27a1779a8a8c323a307ac8a70bc4489d
   
   # begin with 10000, smallest 5 digit no.
list = []
i = 10000
sum = 0
while i < 100000:
	print "Trying with ", i
	num = i
	while i < 0:
	   digit = num % 10
	   sum = sum + (digit ** 5)
	   num = num / 10
	if  sum == i:
		  print sum
		  list.append(sum)
	sum = 0
	i = i + 1	
	   			  
